/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controlador.AlumnoData;
import java.awt.HeadlessException;
import java.sql.Date;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Alumno;
import modelo.Conexion;
import modelo.Materia;

/**
 *
 * @author Caro_Z
 */
public class ViewListadoDeAlumnos extends javax.swing.JInternalFrame {

    Conexion conexion = new Conexion();

    private ArrayList<Alumno> listaAlumnosA;
    private ArrayList<Alumno> listaAlumnosI;
    private AlumnoData alumnoData;
    private DefaultTableModel modelo;

    public ViewListadoDeAlumnos() {
        initComponents();

        alumnoData = new AlumnoData(conexion);

        conexion = new Conexion();
        alumnoData = new AlumnoData(conexion);
        listaAlumnosA = (ArrayList<Alumno>) alumnoData.listarAlumnosActivos();
        listaAlumnosI = (ArrayList<Alumno>) alumnoData.listarAlumnosInactivos();

        modelo = new DefaultTableModel();
        armaCabeceraTabla();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        rbActivos = new javax.swing.JRadioButton();
        rbNoActivos = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tAlumnos = new javax.swing.JTable();
        btSalir = new javax.swing.JButton();
        btAlta = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("LISTADO DE ALUMNOS");

        rbActivos.setText("ACTIVOS");
        rbActivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbActivosActionPerformed(evt);
            }
        });

        rbNoActivos.setText("NO ACTIVOS");
        rbNoActivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNoActivosActionPerformed(evt);
            }
        });

        tAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "APELLIDO", "NOMBRE", "FECHA DE NAC", "ACTIVO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tAlumnos);
        if (tAlumnos.getColumnModel().getColumnCount() > 0) {
            tAlumnos.getColumnModel().getColumn(0).setResizable(false);
        }

        btSalir.setText("SALIR");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });

        btAlta.setText("DAR DE ALTA");
        btAlta.setEnabled(false);
        btAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAltaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(127, 127, 127)
                            .addComponent(rbNoActivos)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbActivos))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(160, 160, 160)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbNoActivos)
                    .addComponent(rbActivos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbActivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbActivosActionPerformed
        // TODO add your handling code here:
        rbNoActivos.setSelected(false);
        btAlta.setEnabled(false);
        borraFilasTabla();
        cargaDatosActivos();


    }//GEN-LAST:event_rbActivosActionPerformed

    private void rbNoActivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNoActivosActionPerformed
        // TODO add your handling code here:
        rbActivos.setSelected(false);

        borraFilasTabla();
        cargaDatosInactivos();
        btAlta.setEnabled(true);

    }//GEN-LAST:event_rbNoActivosActionPerformed

    private void btAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAltaActionPerformed
        // TODO add your handling code here:
        try {
            int filaSeleccionada = tAlumnos.getSelectedRow();

            if (filaSeleccionada != -1) {

                int id_alumno = (Integer) modelo.getValueAt(filaSeleccionada, 0);
                String apellido = (String) modelo.getValueAt(filaSeleccionada, 1);
                String nombre = (String) modelo.getValueAt(filaSeleccionada, 2);

                alumnoData.activarAlumno(id_alumno);

                boolean estado = (Boolean) modelo.getValueAt(filaSeleccionada, 4);

                borraFilasTabla();

            } else {
                JOptionPane.showMessageDialog(this, " Debe seleccionar un alumno");

            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(this, " No se puedo dar de alta el alumno");
        }
    }//GEN-LAST:event_btAltaActionPerformed

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btSalirActionPerformed
    private void armaCabeceraTabla() {

        //Titulos de Columnas
        ArrayList<Object> columnas = new ArrayList<Object>();
        columnas.add("ID");
        columnas.add("Apellido");
        columnas.add("Nombre");
        columnas.add("Fecha de Nac");
        columnas.add("Activo");

        for (Object it : columnas) {

            modelo.addColumn(it);
        }
        tAlumnos.setModel(modelo);
    }

    private void borraFilasTabla() {

        int a = modelo.getRowCount() - 1;

        for (int i = a; i >= 0; i--) {

            modelo.removeRow(i);
        }
    }

    private void cargaDatosActivos() {

        borraFilasTabla();
        //Llenar filas con las materias en las que esta incripto un alumno

        ArrayList<Alumno> lista = (ArrayList) alumnoData.listarAlumnosActivos();

        for (Alumno a : lista) {

            modelo.addRow(new Object[]{a.getId_alumno(), a.getApellido(), a.getNombre(), a.getFechaNac(), a.isActivo()});
        }
    }

    private void cargaDatosInactivos() {

        borraFilasTabla();
        //Llenar filas con las materias en las que esta incripto un alumno

        ArrayList<Alumno> lista = (ArrayList) alumnoData.listarAlumnosInactivos();

        for (Alumno a : lista) {

            modelo.addRow(new Object[]{a.getId_alumno(), a.getApellido(), a.getNombre(), a.getFechaNac(), a.isActivo()});
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlta;
    private javax.swing.JButton btSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbActivos;
    private javax.swing.JRadioButton rbNoActivos;
    private javax.swing.JTable tAlumnos;
    // End of variables declaration//GEN-END:variables
}
