/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controlador.MateriaData;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Conexion;
import modelo.Materia;

/**
 *
 * @author Caro_Z
 */
public class ViewListadoDeMaterias extends javax.swing.JInternalFrame {

    Conexion conexion = new Conexion();
    private DefaultTableModel modelo;
    private List<Materia> listaMateriasA;
    private MateriaData materiaData;
    private List<Materia> listaMateriasI;

    public ViewListadoDeMaterias() {
        initComponents();
        conexion = new Conexion();
        materiaData = new MateriaData(conexion);
        listaMateriasA = (ArrayList) materiaData.listarMateriasActivas();
        listaMateriasI = (ArrayList) materiaData.listarMateriasInactivas();

        modelo = new DefaultTableModel();
        armaCabeceraTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btAlta = new javax.swing.JButton();
        btSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tMaterias = new javax.swing.JTable();
        rbActivas = new javax.swing.JRadioButton();
        rbNoActivas = new javax.swing.JRadioButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("LISTADO DE MATERIAS");

        btAlta.setText("DAR DE ALTA");
        btAlta.setEnabled(false);
        btAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAltaActionPerformed(evt);
            }
        });

        btSalir.setText("SALIR");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });

        tMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "AÑO", "ACTIVA"
            }
        ));
        jScrollPane1.setViewportView(tMaterias);

        rbActivas.setText("ACTIVAS");
        rbActivas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbActivasActionPerformed(evt);
            }
        });

        rbNoActivas.setText("NO ACTIVAS");
        rbNoActivas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNoActivasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(rbActivas)
                        .addGap(91, 91, 91)
                        .addComponent(rbNoActivas))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(btAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbActivas)
                    .addComponent(rbNoActivas))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbActivasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbActivasActionPerformed
        // TODO add your handling code here:
        rbNoActivas.setSelected(false);
        btAlta.setEnabled(false);
        borraFilasTabla();
        cargaDatosActivos();

    }//GEN-LAST:event_rbActivasActionPerformed

    private void rbNoActivasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNoActivasActionPerformed
        // TODO add your handling code here:
        rbActivas.setSelected(false);
        btAlta.setEnabled(true);
        borraFilasTabla();
        cargaDatosInactivos();
        
       
    }//GEN-LAST:event_rbNoActivasActionPerformed

    private void btAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAltaActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = tMaterias.getSelectedRow();
  
        if (filaSeleccionada != -1) {

            int id_materia = (Integer) modelo.getValueAt(filaSeleccionada, 0);

            materiaData.activarMateria(id_materia);

            boolean estado = (Boolean) modelo.getValueAt(filaSeleccionada, 3);
            
                       
            borraFilasTabla();

        } else {
            JOptionPane.showMessageDialog(this, " Debe seleccionar una materia");

        }

    }//GEN-LAST:event_btAltaActionPerformed

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btSalirActionPerformed
    private void armaCabeceraTabla() {

        //Titulos de Columnas
        ArrayList<Object> columnas = new ArrayList<Object>();
        columnas.add("ID");
        columnas.add("Nombre");
        columnas.add("Año");
        columnas.add("Activo");

        for (Object it : columnas) {

            modelo.addColumn(it);
        }
        tMaterias.setModel(modelo);
    }

    private void borraFilasTabla() {

        int a = modelo.getRowCount() - 1;

        for (int i = a; i >= 0; i--) {

            modelo.removeRow(i);
        }
    }

    private void cargaDatosActivos() {

        borraFilasTabla();
        //Llenar filas con las materias en las que esta incripto un alumno

        ArrayList<Materia> lista = (ArrayList) materiaData.listarMateriasActivas();

        for (Materia a : lista) {

            modelo.addRow(new Object[]{a.getId_materia(), a.getNombre(), a.getAnio(), a.isActivo()});
        }
    }

    private void cargaDatosInactivos() {

        borraFilasTabla();
        //Llenar filas con las materias en las que esta incripto un alumno

        ArrayList<Materia> lista = (ArrayList) materiaData.listarMateriasInactivas();

        for (Materia a : lista) {

            modelo.addRow(new Object[]{a.getId_materia(), a.getNombre(), a.getAnio(), a.isActivo()});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlta;
    private javax.swing.JButton btSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbActivas;
    private javax.swing.JRadioButton rbNoActivas;
    private javax.swing.JTable tMaterias;
    // End of variables declaration//GEN-END:variables
}
